# Generated by Django 5.0.3 on 2024-12-17 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carrito',
            fields=[
                ('idCarrito', models.BigAutoField(primary_key=True, serialize=False)),
                ('total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='coleccion',
            fields=[
                ('idColeccion', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('idDescuento', models.AutoField(primary_key=True, serialize=False)),
                ('codigoDescuento', models.CharField(max_length=50, unique=True)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('pago_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pago', models.CharField(max_length=50)),
                ('fecha_venta', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('idUsuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('rol', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CarritoDescuento',
            fields=[
                ('idCarritoDescuento', models.AutoField(primary_key=True, serialize=False)),
                ('idCarrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funko_import.carrito')),
                ('idDescuento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funko_import.descuento')),
            ],
        ),
        migrations.CreateModel(
            name='CodigoSeguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('idFactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funko_import.factura')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaDescuento',
            fields=[
                ('idFacturaDescuento', models.AutoField(primary_key=True, serialize=False)),
                ('idDescuento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funko_import.descuento')),
                ('idFactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funko_import.factura')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('nombreEdicion', models.CharField(max_length=100)),
                ('esEspecial', models.BooleanField(default=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('brilla', models.BooleanField(default=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidadDisp', models.IntegerField()),
                ('URLImagen', models.CharField(max_length=2083)),
                ('idColeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funko_import.coleccion')),
            ],
        ),
        migrations.CreateModel(
            name='LineaFactura',
            fields=[
                ('idLineaFactura', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('idFactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funko_import.factura')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funko_import.producto')),
            ],
        ),
        migrations.CreateModel(
            name='IngresoStock',
            fields=[
                ('idStock', models.AutoField(primary_key=True, serialize=False)),
                ('cantidadIngresa', models.IntegerField()),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funko_import.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoCarrito',
            fields=[
                ('id_producto_carrito', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funko_import.carrito')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funko_import.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id_promocion', models.AutoField(primary_key=True, serialize=False)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funko_import.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ResenaComentario',
            fields=[
                ('idResenaComentario', models.AutoField(primary_key=True, serialize=False)),
                ('resena', models.IntegerField()),
                ('comentario', models.CharField(max_length=500)),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funko_import.producto')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funko_import.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.TextField(max_length=255)),
                ('respuesta', models.TextField(max_length=255, null=True)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funko_import.producto')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funko_import.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PeticionProducto',
            fields=[
                ('id_peticion', models.AutoField(primary_key=True, serialize=False)),
                ('peticion', models.TextField(max_length=500)),
                ('correo', models.EmailField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('fecha_pedido', models.DateField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funko_import.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funko_import.usuario'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funko_import.usuario'),
        ),
    ]
