# Generated by Django 5.0.3 on 2024-12-30 21:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funko_import', '0003_alter_descuento_porcentaje_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productocarrito',
            name='precio',
        ),
        migrations.AlterField(
            model_name='coleccion',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombreEdicion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='numero',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
