# Generated by Django 5.0.3 on 2025-01-15 21:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funko_import', '0004_remove_productocarrito_precio_alter_coleccion_nombre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codigoseguimiento',
            old_name='idFactura',
            new_name='id_factura',
        ),
        migrations.RenameField(
            model_name='facturadescuento',
            old_name='idFactura',
            new_name='id_factura',
        ),
        migrations.RenameField(
            model_name='lineafactura',
            old_name='idFactura',
            new_name='id_factura',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_original',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterUniqueTogether(
            name='carritodescuento',
            unique_together={('idCarrito', 'idDescuento')},
        ),
    ]
