# Generated by Django 5.0.3 on 2025-02-14 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funko_import', '0006_lineafactura_preciounitario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='idColeccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='funko_import.coleccion'),
        ),
    ]
