# Generated by Django 5.0.3 on 2025-02-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funko_import', '0007_alter_producto_idcoleccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edicion',
            fields=[
                ('idEdicion', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
