# Generated by Django 5.0.3 on 2025-02-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funko_import', '0009_rename_idedicion_edicion_id_edicion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='URLImagen',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
