# Generated by Django 5.0.3 on 2025-02-19 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funko_import', '0011_producto_idedicion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='nombreEdicion',
        ),
        migrations.AlterField(
            model_name='producto',
            name='idEdicion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='funko_import.edicion'),
        ),
    ]
