# Generated by Django 5.0.3 on 2025-02-20 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funko_import', '0012_remove_producto_nombreedicion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='funko_import.producto'),
        ),
    ]
