# Generated by Django 5.0.3 on 2025-02-20 21:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funko_import', '0014_alter_promocion_id_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('1.00'))]),
        ),
    ]
