# Generated by Django 5.0.3 on 2025-02-21 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funko_import', '0017_alter_usuario_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='token',
        ),
    ]
