# Generated by Django 5.0.3 on 2025-02-22 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funko_import', '0019_alter_carrito_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='total',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
