# Generated by Django 5.0.3 on 2025-02-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funko_import', '0021_alter_carrito_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='respuesta',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
