# Generated by Django 5.0.3 on 2025-02-24 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funko_import', '0023_alter_pregunta_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha_venta',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lineafactura',
            name='id_factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas_factura', to='funko_import.factura'),
        ),
    ]
